import hard from '../../image/popular-sets/hard.png';
import aroundSet from '../../image/popular-sets/aroundSet.png';
import beauty from '../../image/popular-sets/beauty.png';
import bigSet from '../../image/popular-sets/BigSet.png';
import setTo9 from '../../image/popular-sets/setTo9.png';
import setTo16 from '../../image/popular-sets/SetTo16.png';

import bigPiramida from '../../image/popular-sets/bigPiramida.png';
import piramida from '../../image/popular-sets/piramida.png';
import forGuests from '../../image/popular-sets/forGuests.png';
import henParty from '../../image/popular-sets/hen-party.png';
import name from '../../image/popular-sets/name.png';
import child1 from '../../image/popular-sets/child1.jpg';
import child2 from '../../image/popular-sets/child2.jpg';
import child3 from '../../image/popular-sets/child3.jpg';
import child4 from '../../image/popular-sets/child4.jpg';
import child5 from '../../image/popular-sets/child5.png';
import child6 from '../../image/popular-sets/child6.jpg';
import child8 from '../../image/popular-sets/child8.webp';
import feb1 from '../../image/popular-sets/feb1.jpg';
import feb3 from '../../image/popular-sets/feb3.jpg';
import korp1 from '../../image/popular-sets/korp1.webp';
import korp2 from '../../image/popular-sets/korp2.jpg';
import korp4 from '../../image/popular-sets/korp4.jpg';
import korp3 from '../../image/popular-sets/korp3.jpg';
import korp5 from '../../image/popular-sets/korp5.jpg';
import korp6 from '../../image/popular-sets/korp6.jpg';
import man1 from '../../image/popular-sets/man1.jpg';
import man2 from '../../image/popular-sets/korp5.jpg';
import man3 from '../../image/popular-sets/man3.jpg';
import mart1 from '../../image/popular-sets/mart1.jpeg';
import mart2 from '../../image/popular-sets/mart2.jpg';
import mart3 from '../../image/popular-sets/mart3.jpg';
import mart4 from '../../image/popular-sets/mart4.jpg';
import mart5 from '../../image/popular-sets/mart5.jpg';

const productsPopular = [
    {
        vendorCode: '1',
        type: 'popular',
        srcProduct: hard,
        altProduct: 'Изображение сердца',
        title: 'Сердце',
        description: '24 штуки в коробке в виде сердца. Ассорти из 6 вкусов',
        productPrice: 2800,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Кондитерское изделие макаронс в виде сердца',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е124, Е150d, ароматизаторы: ванилин, банан, клубника, карамель, манго, виноград',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 4,
            orange: 4,
            tangerine: 4,
            chocolate: 8,
        },
    },
    {
        vendorCode: '2',
        type: 'popular',
        srcProduct: aroundSet,
        altProduct: 'Изображение круглого набора',
        title: 'Круглый набор',
        description: '40 макаронс в круглой коробке с персональной надписью',
        productPrice: 3900,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс в круглой коробке с персональной надписью',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е124, Е150d, ароматизаторы: ванилин, клубника, манго, виноград',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 7,
            orange: 7,
            tangerine: 7,
            chocolate: 19,
        },
    },
    {
        vendorCode: '3',
        type: 'popular',
        srcProduct: beauty,
        altProduct: 'Изображение макаронс',
        title: 'Красота спасёт мир',
        description: 'Набор 16 шт. Вкусы: клубника - базилик, кокос, голубой сыр, пармезан',
        productPrice: 750,
        delivery: false,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс вкусов: клубника - базилик, кокос, голубой сыр, пармезан',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е124, Е150d, ароматизаторы: ванилин, клубника, кокос, сырный',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 3,
            orange: 3,
            tangerine: 3,
            chocolate: 7,
        },
    },
    {
        vendorCode: '4',
        type: 'popular',
        srcProduct: setTo9,
        altProduct: 'Изображение набора макаронс из 9шт',
        title: 'Набор на 9',
        description: 'Набор из 9 штук в квадратной коробке. Вкусы: шоколад, фисташка, вишня',
        productPrice: 950,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс вкусов: шоколад, фисташка, вишня',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е150d, ароматизаторы: ванилин, шоколадный, фисташковый, вишневый',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 6,
            orange: 6,
            tangerine: 6,
            chocolate: 22,
        },
    },
    {
        vendorCode: "5",
        type: 'popular',
        srcProduct: setTo16,
        altProduct: "Изображение набора макаронс из 16шт",
        title: "Набор на 16",
        description:
            "Набор 16 шт. Вкусы: соленая карамель, голубой сыр, пармезан, шоколад",
        productPrice: "1500",
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: "Описание продукта",
        compound: "Состав продукта",
        storageCondition: "Условия хранения",
        tastes: {
            apple: 0,
            orange: 0,
            tangerine: 0,
            chocolate: 16,
        },
    },
    {
        vendorCode: "6",
        type: 'popular',
        srcProduct: bigSet,
        altProduct: "Изображение большого набора макаронс",
        title: "Круглый набор",
        description: "40 макаронс в круглой коробке с персональной надписью",
        productPrice: "3900",
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: "Описание продукта",
        compound: "Состав продукта",
        storageCondition: "Условия хранения",
        tastes: {
            apple: 15,
            orange: 10,
            tangerine: 5,
            chocolate: 10,
        },
    },
    {
        vendorCode: '7',
        type: 'popular',
        srcProduct: setTo9,
        altProduct: 'Изображение набора макаронс из 9шт',
        title: 'Набор на 9',
        description: 'Набор из 9 штук в квадратной коробке. Вкусы: шоколад, фисташка, вишня',
        productPrice: 950,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс вкусов: шоколад, фисташка, вишня',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е150d, ароматизаторы: ванилин, шоколадный, фисташковый, вишневый',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 6,
            orange: 6,
            tangerine: 6,
            chocolate: 22,
        },
    },
    {
        vendorCode: '8',
        type: 'popular',
        srcProduct: beauty,
        altProduct: 'Изображение макаронс',
        title: 'Красота спасёт мир',
        description: 'Набор 16 шт. Вкусы: клубника - базилик, кокос, голубой сыр, пармезан',
        productPrice: 750,
        delivery: false,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс вкусов: клубника - базилик, кокос, голубой сыр, пармезан',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е124, Е150d, ароматизаторы: ванилин, клубника, кокос, сырный',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 3,
            orange: 3,
            tangerine: 3,
            chocolate: 7,
        },
    },
    {
        vendorCode: '9',
        srcProduct: bigPiramida,
        type: 'wedding',
        altProduct: 'Изображение большой пирамиды макарунс',
        title: 'Большая пирамида',
        description: 'Импозантная пирамида из 120 макарунс на ваше великолепное мероприятие',
        productPrice: 9000,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Импозантная пирамида из 120 макарунс на ваше великолепное мероприятие',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 30,
            strawberry: 30,
            vanilla: 30,
            pistachio: 30,
        },
    },
    {
        vendorCode: '10',
        srcProduct: piramida,
        type: 'wedding',
        altProduct: 'Изображение пирамиды макарунс',
        title: 'Пирамида макарунс',
        description: 'Красочная пирамида из 60 макарунс с разнообразными вкусами',
        productPrice: 5000,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Красочная пирамида из 60 макарунс с разнообразными вкусами',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 20,
            raspberry: 15,
            lemon: 10,
            coconut: 15,
        },
    },
    {
        vendorCode: '11',
        srcProduct: forGuests,
        type: 'wedding',
        altProduct: 'Изображение макарунс для гостей',
        title: 'Макаруны для гостей',
        description: 'Индивидуальные наборы макарунс для каждого гостя на вашем торжестве',
        productPrice: 1300,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Индивидуальные наборы макарунс для каждого гостя на вашем торжестве',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 12,
            vanilla: 12,
            strawberry: 12,
            pistachio: 12,
        },
    },
    {
        vendorCode: '12',
        srcProduct: henParty,
        type: 'wedding',
        altProduct: 'Изображение макарунс для девичника',
        title: 'Макаруны для девичника',
        description: 'Оригинальные макарунс для яркого и веселого девичника',
        productPrice: 1800,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Оригинальные макарунс для яркого и веселого девичника',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            raspberry: 15,
            passionFruit: 10,
            blueberry: 10,
            lime: 10,
        },
    },
    {
        vendorCode: '13',
        srcProduct: name,
        type: 'wedding',
        altProduct: 'Изображение макарунс с именами',
        title: 'Макаруны с именами',
        description: 'Уникальные макарунс с именами ваших гостей',
        productPrice: 2500,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Уникальные макарунс с именами ваших гостей',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 10,
            raspberry: 10,
            lemon: 10,
            vanilla: 10,
        },
    },
    {
        vendorCode: '14',
        type: 'wedding',
        srcProduct: hard,
        altProduct: 'Изображение сердца',
        title: 'Сердце',
        description: '24 штуки в коробке в виде сердца. Ассорти из 6 вкусов. Прекрасный выбор для любого праздника',
        productPrice: 2800,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Кондитерское изделие макаронс в виде сердца',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е124, Е150d, ароматизаторы: ванилин, банан, клубника, карамель, манго, виноград',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 4,
            orange: 4,
            tangerine: 4,
            chocolate: 8,
        },
    },
    {
        vendorCode: '15',
        srcProduct: piramida,
        type: 'wedding',
        altProduct: 'Изображение пирамиды макарунс',
        title: 'Пирамида макарунс',
        description: 'Красочная пирамида из 60 макарунс с разнообразными вкусами',
        productPrice: 5000,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Красочная пирамида из 60 макарунс с разнообразными вкусами',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 20,
            raspberry: 15,
            lemon: 10,
            coconut: 15,
        },
    },
    {
        vendorCode: '16',
        srcProduct: forGuests,
        type: 'wedding',
        altProduct: 'Изображение макарунс для гостей',
        title: 'Макаруны для гостей',
        description: 'Индивидуальные наборы макарунс для каждого гостя на вашем торжестве',
        productPrice: 1300,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Индивидуальные наборы макарунс для каждого гостя на вашем торжестве',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 12,
            vanilla: 12,
            strawberry: 12,
            pistachio: 12,
        },
    },
    {
        vendorCode: '17',
        srcProduct: henParty,
        type: 'wedding',
        altProduct: 'Изображение макарунс для девичника',
        title: 'Макаруны для девичника',
        description: 'Оригинальные макарунс для яркого и веселого девичника',
        productPrice: 1800,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Оригинальные макарунс для яркого и веселого девичника',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            raspberry: 15,
            passionFruit: 10,
            blueberry: 10,
            lime: 10,
        },
    },
    {
        vendorCode: '18',
        type: 'childrens_party',
        srcProduct: child1,
        altProduct: 'Детское счастье',
        title: 'Детское счастье',
        description: '20 штуки в коробке в виде сердца. Ассорти из 6 вкусов',
        productPrice: 2800,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Кондитерское изделие макаронс в виде сердца',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е124, Е150d, ароматизаторы: ванилин, банан, клубника, карамель, манго, виноград',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 4,
            orange: 4,
            tangerine: 4,
            chocolate: 8,
        }
    },
    {
        vendorCode: '19',
        type: 'childrens_party',
        srcProduct: child2,
        altProduct: 'Изображение мороженого',
        title: 'Наслаждение',
        description: '16 штук в коробке в виде мороженого. Ассорти из 4 вкусов',
        productPrice: 2500,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс в виде мороженого',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, шоколад, клубника, лимон',
        storageCondition: 'Хранить при температуре от -18 градусов Цельсия',
        tastes: {
            vanilla: 4,
            chocolate: 4,
            strawberry: 4,
            lemon: 4,
        }
    },
    {
        vendorCode: '20',
        type: 'childrens_party',
        srcProduct: child3,
        altProduct: 'Изображение макарунс',
        title: 'Звезда',
        description: '20 штук в коробке в виде звезды. Ассорти из 5 вкусов',
        productPrice: 2600,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Кондитерское изделие макаронс в виде звезды',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, клубника, манго, ананас, мятное',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            strawberry: 4,
            mango: 4,
            pineapple: 4,
            mint: 4,
        }
    },
    {
        vendorCode: '21',
        type: 'childrens_party',
        srcProduct: child4,
        altProduct: 'Изображение цветка',
        title: 'Цветок',
        description: '18 штук в коробке в виде цветка. Ассорти из 4 вкусов',
        productPrice: 2700,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс в виде цветка',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, клубника, шоколад, лимон',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            strawberry: 4,
            chocolate: 4,
            lemon: 6,
        }
    },
    {
        vendorCode: '22',
        type: 'childrens_party',
        srcProduct: child5,
        altProduct: 'Изображение медведя',
        title: 'Медвежонок',
        description: '28 штук в коробке в виде медвежонка. Ассорти из 7 вкусов',
        productPrice: 3200,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс в виде медвежонка',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, клубника, манго, апельсин, черника, киви, груша',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            strawberry: 4,
            mango: 4,
            orange: 4,
            blueberry: 4,
            kiwi: 4,
            pear: 4,
        }
    },
    {
        vendorCode: '23',
        type: 'childrens_party',
        srcProduct: child6,
        altProduct: 'Изображение животных',
        title: "Зверюшки",
        description: '32 штуки в коробке в виде разных животных. Ассорти из 8 вкусов',
        productPrice: 3500,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Кондитерское изделие макаронс в виде разных животных',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, клубника, шоколад, лимон, апельсин, мята, черника, карамель',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            strawberry: 4,
            chocolate: 4,
            lemon: 4,
            orange: 4,
            mint: 4,
            blueberry: 4,
            caramel: 4,
        }
    },
    {
        vendorCode: '25',
        type: 'childrens_party',
        srcProduct: child8,
        altProduct: 'Изображение автомобиля',
        title: 'Автомобиль',
        description: '28 штук в коробке в виде автомобиля. Ассорти из 7 вкусов',
        productPrice: 3400,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Кондитерское изделие макаронс в виде автомобиля',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, клубника, шоколад, апельсин, карамель, манго, ананас',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            strawberry: 4,
            chocolate: 4,
            orange: 4,
            caramel: 4,
            mango: 4,
            pineapple: 4,
        }
    },
    {
        vendorCode: '26',
        type: 'valentines_day',
        srcProduct: feb1,
        altProduct: 'Изображение ',
        title: 'Моя любовь',
        description: '24 штуки в коробке. Ассорти из 6 вкусов',
        productPrice: 2800,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Кондитерское изделие макаронс',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е124, Е150d, ароматизаторы: ванилин, банан, клубника, карамель, манго, виноград',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 4,
            orange: 4,
            tangerine: 4,
            chocolate: 8,
        }
    },
    {
        vendorCode: '27',
        type: 'valentines_day',
        srcProduct: piramida,
        altProduct: 'Изображение набора',
        title: 'Побалуй меня',
        description: '40 макаронс в  коробке с персональной надписью',
        productPrice: 3900,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс в коробке с персональной надписью',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е124, Е150d, ароматизаторы: ванилин, клубника, манго, виноград',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 7,
            orange: 7,
            tangerine: 7,
            chocolate: 19,
        }
    },
    {
        vendorCode: '28',
        type: 'valentines_day',
        srcProduct: feb3,
        altProduct: 'Изображение макаронс',
        title: 'Сердечки в глазах',
        description: 'Набор 16 шт. Вкусы: клубника - базилик, кокос, голубой сыр, пармезан',
        productPrice: 3270,
        delivery: false,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс вкусов: клубника - базилик, кокос, голубой сыр, пармезан',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е124, Е150d, ароматизаторы: ванилин, клубника, кокос, сырный',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 3,
            orange: 3,
            tangerine: 3,
            chocolate: 7,
        }
    },
    {
        vendorCode: '29',
        type: 'corporate_event',
        srcProduct: korp1,
        altProduct: 'Изображение галстука',
        title: 'Бизнес-галстук',
        description: '32 стильных макаронс в форме галстука. Ассорти из 8 деловых вкусов',
        productPrice: 3500,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Элегантные макаронс в форме галстука для вашего корпоративного мероприятия.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: кофе, ваниль, карамель, шоколад, миндаль, фисташка, мокка, корица',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            coffee: 4,
            vanilla: 4,
            caramel: 4,
            chocolate: 4,
            almond: 4,
            pistachio: 4,
            mocha: 4,
            cinnamon: 4,
        }
    },
    {
        vendorCode: '30',
        type: 'corporate_event',
        srcProduct: korp2,
        altProduct: 'Изображение квадрата',
        title: 'Сфера влияния',
        description: '28 креативных макаронс в форме квадрата. Ассорти из 7 вдохновляющих вкусов',
        productPrice: 3200,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Уникальные макаронс в форме квадрата для поднятия настроения на вашем корпоративе.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, клубника, малина, лимон, апельсин, черника, мята',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            strawberry: 4,
            raspberry: 4,
            lemon: 4,
            orange: 4,
            blueberry: 4,
            mint: 4,
        }
    },
    {
        vendorCode: '31',
        type: 'corporate_event',
        srcProduct: korp3,
        altProduct: 'Изображение смайла',
        title: 'Позитивное настроение',
        description: '36 ярких макаронс в форме смайла. Ассорти из 9 радостных вкусов',
        productPrice: 3800,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Веселые макаронс в форме смайла, чтобы ваши сотрудники улыбались во время корпоративных мероприятий.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: клубника, лимон, апельсин, вишня, ананас, грейпфрут, киви, манго, малина',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            strawberry: 4,
            lemon: 4,
            orange: 4,
            cherry: 4,
            pineapple: 4,
            grapefruit: 4,
            kiwi: 4,
            mango: 4,
            raspberry: 4,
        }
    },
    {
        vendorCode: '32',
        type: 'corporate_event',
        srcProduct: korp4,
        altProduct: 'Изображение звезды',
        title: 'Звездный успех',
        description: '20 блестящих макаронс в форме звезды. Ассорти из 5 благоприятных вкусов',
        productPrice: 3000,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Сияющие макаронс в форме звезды для отметки ваших корпоративных достижений.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, карамель, малина, апельсин, лимон',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            caramel: 4,
            raspberry: 4,
            orange: 4,
            lemon: 4,
        }
    },
    {
        vendorCode: '33',
        type: 'corporate_event',
        srcProduct: korp5,
        altProduct: 'Изображение пазла',
        title: 'Корпоративный пазл',
        description: '24 уникальных макаронс в форме пазла. Ассорти из 6 интригующих вкусов',
        productPrice: 3400,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Загадочные макаронс в форме пазла, чтобы собрать ваши корпоративные мероприятия воедино.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: шоколад, кофе, карамель, орех, ваниль, кокос',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            chocolate: 4,
            coffee: 4,
            caramel: 4,
            nut: 4,
            vanilla: 4,
            coconut: 4,
        }
    },
    {
        vendorCode: '34',
        type: 'corporate_event',
        srcProduct: korp6,
        altProduct: 'Изображение часов',
        title: 'Время успеха',
        description: '18 макаронс в форме часов. Ассорти из 4 вкусов, каждый по своему времени суток',
        productPrice: 3100,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме часов, чтобы вдохновлять на успех в любое время дня.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: кофе, ваниль, молоко, какао',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            coffee: 4,
            vanilla: 4,
            milk: 4,
            cocoa: 6,
        }
    },
    {
        vendorCode: '35',
        type: 'corporate_event',
        srcProduct: korp4,
        altProduct: 'Изображение звезды',
        title: 'Звездный успех',
        description: '20 блестящих макаронс в форме звезды. Ассорти из 5 благоприятных вкусов',
        productPrice: 3000,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Сияющие макаронс в форме звезды для отметки ваших корпоративных достижений.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, карамель, малина, апельсин, лимон',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            caramel: 4,
            raspberry: 4,
            orange: 4,
            lemon: 4,
        }
    },
    {
        vendorCode: '36',
        type: 'corporate_event',
        srcProduct: korp5,
        altProduct: 'Изображение пазла',
        title: 'Корпоративный пазл',
        description: '24 уникальных макаронс в форме пазла. Ассорти из 6 интригующих вкусов',
        productPrice: 3400,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Загадочные макаронс в форме пазла, чтобы собрать ваши корпоративные мероприятия воедино.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: шоколад, кофе, карамель, орех, ваниль, кокос',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            chocolate: 4,
            coffee: 4,
            caramel: 4,
            nut: 4,
            vanilla: 4,
            coconut: 4,
        }
    },
    {
        vendorCode: '37',
        type: 'corporate_event',
        srcProduct: korp6,
        altProduct: 'Изображение часов',
        title: 'Время успеха',
        description: '18 макаронс в форме часов. Ассорти из 4 вкусов, каждый по своему времени суток',
        productPrice: 3100,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме часов, чтобы вдохновлять на успех в любое время дня.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: кофе, ваниль, молоко, какао',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            coffee: 4,
            vanilla: 4,
            milk: 4,
            cocoa: 6,
        }
    },
    {
        vendorCode: '38',
        type: 'defenders_day',
        srcProduct: man1,
        altProduct: 'Изображение звезды',
        title: 'Героический полет',
        description: '30 макаронс в форме звезды. Ассорти из 7 вкусов, каждый символизирует силу и мужество',
        productPrice: 3400,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Символичные макаронс в форме звезды, чтобы отметить героический день.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: кофе, какао, ваниль, орех, карамель, клубника, лимон',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            coffee: 4,
            cocoa: 4,
            vanilla: 4,
            nut: 4,
            caramel: 4,
            strawberry: 4,
            lemon: 4,
        }
    },
    {
        vendorCode: '39',
        type: 'defenders_day',
        srcProduct: man2,
        altProduct: 'Изображение танка',
        title: 'Железная дружба',
        description: '24 макаронс в форме танка. Ассорти из 6 мужественных вкусов, каждый как составная часть сильной команды',
        productPrice: 3200,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме танка, чтобы праздновать дружбу и солидарность в важные моменты.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: шоколад, кофе, мокка, ваниль, карамель, орех',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            chocolate: 4,
            coffee: 4,
            mocha: 4,
            vanilla: 4,
            caramel: 4,
            nut: 4,
        }
    },
    {
        vendorCode: '40',
        type: 'defenders_day',
        srcProduct: man3,
        altProduct: 'Изображение медали',
        title: 'Медаль за отвагу',
        description: '28 макаронс в форме медали. Ассорти из 7 смелых вкусов, каждый вкус – награда за мужество',
        productPrice: 3300,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме медали, чтобы почтить доблесть и смелость на Дне защитника Отечества.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: малина, грейпфрут, апельсин, лимон, ананас, вишня, мята',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            raspberry: 4,
            grapefruit: 4,
            orange: 4,
            lemon: 4,
            pineapple: 4,
            cherry: 4,
            mint: 4,
        }
    },
    {
        vendorCode: '41',
        type: 'womens_day',
        srcProduct: mart1,
        altProduct: 'Изображение цветка',
        title: 'Цветущая нежность',
        description: '28 макаронс в форме сердца с цветочным декором. Ассорти из 7 нежных вкусов, каждый – как цветок к женскому обаянию',
        productPrice: 3200,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме сердца с цветочным декором, чтобы отметить восхитительное влияние женственности.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: роза, лаванда, виолетовый бутон, жасмин, ирис, орхидея, магнолия',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            rose: 4,
            lavender: 4,
            violet: 4,
            jasmine: 4,
            iris: 4,
            orchid: 4,
            magnolia: 4,
        }
    },
    {
        vendorCode: '42',
        type: 'womens_day',
        srcProduct: mart2,
        altProduct: 'Изображение лаконичных линий',
        title: 'Элегантная грация',
        description: '24 макаронс в форме круга с лаконичными линиями. Ассорти из 6 изысканных вкусов, каждый – подчеркнутая грация женщины',
        productPrice: 3100,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс с лаконичными линиями в форме круга, чтобы увековечить непередаваемую грацию женщин.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, клубника, малина, черника, мята, лимон',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            strawberry: 4,
            raspberry: 4,
            blueberry: 4,
            mint: 4,
            lemon: 4,
        }
    },
    {
        vendorCode: '43',
        type: 'womens_day',
        srcProduct: mart3,
        altProduct: 'Изображение кофейной чашки',
        title: 'Вдохновляющий аромат',
        description: '32 макаронс в форме кофейной чашки. Ассорти из 8 изысканных вкусов, каждый – как аромат кофейного утра',
        productPrice: 3400,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме кофейной чашки с ароматами кофейного утра, чтобы вдохновить и поблагодарить.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: кофе, ваниль, какао, карамель, орех, молоко, кокос, миндаль',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            coffee: 4,
            vanilla: 4,
            cocoa: 4,
            caramel: 4,
            nut: 4,
            milk: 4,
            coconut: 4,
            almond: 4,
        }
    },
    {
        vendorCode: '44',
        type: 'womens_day',
        srcProduct: mart4,
        altProduct: 'Изображение подковы',
        title: 'Удача и радость',
        description: '36 макаронс в форме подковы. Ассорти из 9 счастливых вкусов, каждый – символ удачи и радости',
        productPrice: 3500,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме подковы, чтобы подарить удачу и радость на Международный женский день.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: клубника, малина, вишня, апельсин, лимон, грейпфрут, манго, киви, гранат',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            strawberry: 4,
            raspberry: 4,
            cherry: 4,
            orange: 4,
            lemon: 4,
            grapefruit: 4,
            mango: 4,
            kiwi: 4,
            pomegranate: 4,
        }
    },
    {
        vendorCode: '45',
        type: 'womens_day',
        srcProduct: mart5,
        altProduct: 'Изображение звезды',
        title: 'Сияние таланта',
        description: '20 макаронс в форме звезды. Ассорти из 5 ярких вкусов, каждый – сверкающая звезда таланта',
        productPrice: 3000,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме звезды, чтобы подчеркнуть талант и яркость женщин в этот особенный день.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, клубника, малина, лимон, апельсин',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            strawberry: 4,
            raspberry: 4,
            lemon: 4,
            orange: 4,
        }
    },
    {
        vendorCode: '46',
        type: 'womens_day',
        srcProduct: mart5,
        altProduct: 'Изображение бабочки',
        title: 'Вольный полет',
        description: '22 макаронс в форме круга с бабочковым декором. Ассорти из 6 вдохновляющих вкусов, каждый – символ вольного духа',
        productPrice: 3300,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме круга с бабочковым декором, чтобы подчеркнуть вольный и свободный дух женщин.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: клубника, лимон, апельсин, вишня, ананас, малина',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            strawberry: 4,
            lemon: 4,
            orange: 4,
            cherry: 4,
            pineapple: 4,
            raspberry: 4,
        }
    },
    {
        vendorCode: '47',
        type: 'womens_day',
        srcProduct: mart2,
        altProduct: 'Изображение лаконичных линий',
        title: 'Элегантная грация',
        description: '24 макаронс в форме круга с лаконичными линиями. Ассорти из 6 изысканных вкусов, каждый – подчеркнутая грация женщины',
        productPrice: 3100,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс с лаконичными линиями в форме круга, чтобы увековечить непередаваемую грацию женщин.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, клубника, малина, черника, мята, лимон',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            strawberry: 4,
            raspberry: 4,
            blueberry: 4,
            mint: 4,
            lemon: 4,
        }
    },
    {
        vendorCode: '48',
        type: 'womens_day',
        srcProduct: mart3,
        altProduct: 'Изображение кофейной чашки',
        title: 'Вдохновляющий аромат',
        description: '32 макаронс в форме кофейной чашки. Ассорти из 8 изысканных вкусов, каждый – как аромат кофейного утра',
        productPrice: 3400,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме кофейной чашки с ароматами кофейного утра, чтобы вдохновить и поблагодарить.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: кофе, ваниль, какао, карамель, орех, молоко, кокос, миндаль',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            coffee: 4,
            vanilla: 4,
            cocoa: 4,
            caramel: 4,
            nut: 4,
            milk: 4,
            coconut: 4,
            almond: 4,
        }
    },
    {
        vendorCode: '49',
        type: 'womens_day',
        srcProduct: mart4,
        altProduct: 'Изображение подковы',
        title: 'Удача и радость',
        description: '36 макаронс в форме подковы. Ассорти из 9 счастливых вкусов, каждый – символ удачи и радости',
        productPrice: 3500,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме подковы, чтобы подарить удачу и радость на Международный женский день.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: клубника, малина, вишня, апельсин, лимон, грейпфрут, манго, киви, гранат',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            strawberry: 4,
            raspberry: 4,
            cherry: 4,
            orange: 4,
            lemon: 4,
            grapefruit: 4,
            mango: 4,
            kiwi: 4,
            pomegranate: 4,
        }
    },
    {
        vendorCode: '50',
        type: "graduation",
        srcProduct: korp6,
        altProduct: 'Изображение часов',
        title: 'Время знаний',
        description: '18 макаронс в форме часов. Ассорти из 4 вкусов, каждый – как отдельный урок на пути к успеху',
        productPrice: 3100,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме часов, чтобы вдохновлять на знания и успех в учебе.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: кофе, ваниль, молоко, какао',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            coffee: 4,
            vanilla: 4,
            milk: 4,
            cocoa: 6,
        }
    },
    {
        vendorCode: '51',
        type: 'back_to_school',
        srcProduct: man1,
        altProduct: 'Изображение звезды',
        title: 'Ученик года',
        description: '30 макаронс в форме звезды. Ассорти из 7 вкусов, каждый – символизирует звездное будущее',
        productPrice: 3400,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Символичные макаронс в форме звезды, чтобы почтить учебные достижения.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: кофе, какао, ваниль, орех, карамель, клубника, лимон',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            coffee: 4,
            cocoa: 4,
            vanilla: 4,
            nut: 4,
            caramel: 4,
            strawberry: 4,
            lemon: 4,
        }
    },
    {
        vendorCode: '52',
        type: 'back_to_school',
        srcProduct: man2,
        altProduct: 'Изображение танка',
        title: 'Знания – сила',
        description: '24 макаронс в форме танка. Ассорти из 6 интеллектуальных вкусов, каждый – ключ к знаниям',
        productPrice: 3200,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме танка, чтобы вдохновить на погружение в мир знаний.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: шоколад, кофе, мокка, ваниль, карамель, орех',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            chocolate: 4,
            coffee: 4,
            mocha: 4,
            vanilla: 4,
            caramel: 4,
            nut: 4,
        }
    },
    {
        vendorCode: '53',
        type: 'back_to_school',
        srcProduct: child3,
        altProduct: 'Изображение медали',
        title: 'Знания – награда',
        description: '28 макаронс в форме медали. Ассорти из 7 вдохновляющих вкусов, каждый – награда за усердие',
        productPrice: 3300,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме медали, чтобы поощрить старания и стремление к знаниям.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: малина, грейпфрут, апельсин, лимон, ананас, вишня, мята',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            raspberry: 4,
            grapefruit: 4,
            orange: 4,
            lemon: 4,
            pineapple: 4,
            cherry: 4,
            mint: 4,
        }
    },
    {
        vendorCode: '54',
        type: 'back_to_school',
        srcProduct: child1,
        altProduct: 'Изображение цветка',
        title: 'Цветущее знание',
        description: '28 макаронс в форме сердца с цветочным декором. Ассорти из 7 разнообразных вкусов, каждый – как цветок знаний',
        productPrice: 3200,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме сердца с цветочным декором, чтобы восхищаться разнообразием знаний.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: роза, лаванда, виолетовый бутон, жасмин, ирис, орхидея, магнолия',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            rose: 4,
            lavender: 4,
            violet: 4,
            jasmine: 4,
            iris: 4,
            orchid: 4,
            magnolia: 4,
        }
    },
    {
        vendorCode: '55',
        type: 'back_to_school',
        srcProduct: child2,
        altProduct: 'Изображение лаконичных линий',
        title: 'Линии знаний',
        description: '24 макаронс в форме круга с лаконичными линиями. Ассорти из 6 утонченных вкусов, каждый – как знание в своей области',
        productPrice: 3100,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс с лаконичными линиями в форме круга, чтобы отметить гармонию и утонченность знаний.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, клубника, малина, черника, мята, лимон',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            strawberry: 4,
            raspberry: 4,
            blueberry: 4,
            mint: 4,
            lemon: 4,
        }
    },
    {
        vendorCode: '56',
        type: 'back_to_school',
        srcProduct: man1,
        altProduct: 'Изображение звезды',
        title: 'Ученик года',
        description: '30 макаронс в форме звезды. Ассорти из 7 вкусов, каждый – символизирует звездное будущее',
        productPrice: 3400,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Символичные макаронс в форме звезды, чтобы почтить учебные достижения.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: кофе, какао, ваниль, орех, карамель, клубника, лимон',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            coffee: 4,
            cocoa: 4,
            vanilla: 4,
            nut: 4,
            caramel: 4,
            strawberry: 4,
            lemon: 4,
        }
    },
    {
        vendorCode: '57',
        type: 'back_to_school',
        srcProduct: man2,
        altProduct: 'Изображение танка',
        title: 'Знания – сила',
        description: '24 макаронс в форме танка. Ассорти из 6 интеллектуальных вкусов, каждый – ключ к знаниям',
        productPrice: 3200,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме танка, чтобы вдохновить на погружение в мир знаний.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: шоколад, кофе, мокка, ваниль, карамель, орех',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            chocolate: 4,
            coffee: 4,
            mocha: 4,
            vanilla: 4,
            caramel: 4,
            nut: 4,
        }
    },
    {
        vendorCode: '58',
        srcProduct: bigPiramida,
        type: 'holiday',
        altProduct: 'Изображение большой пирамиды макарунс',
        title: 'Звездопад вкусов',
        description: 'Импозантная пирамида из 120 макарунс с праздничными вкусами на ваше великолепное мероприятие',
        productPrice: 9000,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Импозантная пирамида из 120 макарунс с праздничными вкусами на ваше великолепное мероприятие',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 30,
            strawberry: 30,
            vanilla: 30,
            pistachio: 30,
        },
    },
    {
        vendorCode: '59',
        srcProduct: piramida,
        type: 'holiday',
        altProduct: 'Изображение пирамиды макарунс',
        title: 'Снежные холмы',
        description: 'Красочная пирамида из 60 макарунс с разнообразными праздничными вкусами',
        productPrice: 5000,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Красочная пирамида из 60 макарунс с разнообразными праздничными вкусами',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 20,
            raspberry: 15,
            lemon: 10,
            coconut: 15,
        },
    },
    {
        vendorCode: '60',
        srcProduct: forGuests,
        type: 'holiday',
        altProduct: 'Изображение макарунс для гостей',
        title: 'Сказочные угощения',
        description: 'Индивидуальные наборы макарунс для каждого гостя на вашем новогоднем торжестве',
        productPrice: 1300,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Индивидуальные наборы макарунс для каждого гостя на вашем новогоднем торжестве',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 12,
            vanilla: 12,
            strawberry: 12,
            pistachio: 12,
        },
    },
    {
        vendorCode: '61',
        srcProduct: henParty,
        type: 'holiday',
        altProduct: 'Изображение макарунс для девичника',
        title: 'Веселые вкусы',
        description: 'Оригинальные макарунс для яркого и веселого новогоднего девичника',
        productPrice: 1800,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Оригинальные макарунс для яркого и веселого новогоднего девичника',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            raspberry: 15,
            passionFruit: 10,
            blueberry: 10,
            lime: 10,
        },
    },
    {
        vendorCode: '62',
        srcProduct: name,
        type: 'holiday',
        altProduct: 'Изображение макарунс с именами',
        title: 'Праздничные имена',
        description: 'Уникальные макарунс с именами ваших гостей для волшебного новогоднего вечера',
        productPrice: 2500,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Уникальные макарунс с именами ваших гостей для волшебного новогоднего вечера',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 10,
            raspberry: 10,
            lemon: 10,
            vanilla: 10,
        },
    },
    {
        vendorCode: '63',
        srcProduct: korp1,
        type: 'holiday',
        altProduct: 'Изображение новогодних макарунс',
        title: 'Новогодние сказки',
        description: 'Сладкие макарунс с праздничными вкусами, чтобы сделать новогодний вечер волшебным',
        productPrice: 2800,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Сладкие макарунс с праздничными вкусами, чтобы сделать новогодний вечер волшебным',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 8,
            vanilla: 8,
            raspberry: 8,
            pistachio: 8,
        },
    },
    {
        vendorCode: '64',
        srcProduct: aroundSet,
        type: 'holiday',
        altProduct: 'Изображение зимних макарунс',
        title: 'Зимняя симфония',
        description: 'Макарунс с праздничными вкусами, чтобы создать атмосферу зимней сказки',
        productPrice: 2600,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Макарунс с праздничными вкусами, чтобы создать атмосферу зимней сказки',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 7,
            peppermint: 5,
            cranberry: 6,
            chestnut: 5,
        },
    },
    {
        vendorCode: '65',
        srcProduct: korp3,
        type: 'holiday',
        altProduct: 'Изображение снежинок',
        title: 'Снежные сказки',
        description: 'Макарунс в форме снежинок с праздничными вкусами, чтобы погрузиться в мир сказки',
        productPrice: 2400,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макарунс в форме снежинок с праздничными вкусами, чтобы погрузиться в мир сказки',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            coconut: 6,
            blueberry: 6,
            whiteChocolate: 6,
            gingerbread: 6,
        },
    },
    {
        vendorCode: '66',
        srcProduct: mart4,
        type: 'holiday',
        altProduct: 'Изображение звезды',
        title: 'Звездный салют',
        description: 'Праздничные макарунс в форме звезд для волшебного новогоднего салюта',
        productPrice: 2200,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Праздничные макарунс в форме звезд для волшебного новогоднего салюта',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 6,
            raspberry: 5,
            lemon: 5,
            orange: 5,
        },
    },
    {
        vendorCode: '68',
        type: "graduation",
        srcProduct: korp1,
        altProduct: 'Изображение книги',
        title: 'Книга знаний',
        description: '40 умных макаронс в форме книги. Ассорти из 10 образовательных вкусов',
        productPrice: 3800,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме книги, символизирующей накопленные знания в школе.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, клубника, шоколад, мед, грецкий орех, малина, лимон, карамель, фисташка, апельсин',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            strawberry: 4,
            chocolate: 4,
            honey: 4,
            walnut: 4,
            raspberry: 4,
            lemon: 4,
            caramel: 4,
            pistachio: 4,
            orange: 4,
        }
    },
    {
        vendorCode: '69',
        type: "graduation",
        srcProduct: korp2,
        altProduct: 'Изображение школьного звонка',
        title: 'Школьный звонок',
        description: '30 звонких макаронс в форме школьного звонка. Ассорти из 6 шумных вкусов',
        productPrice: 3300,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме школьного звонка, чтобы вспоминать звонки и уроки.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: клубника, малина, черника, грецкий орех, мед, груша',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            strawberry: 5,
            raspberry: 5,
            blueberry: 5,
            walnut: 5,
            honey: 5,
            pear: 5,
        }
    },
    {
        vendorCode: '70',
        type: "graduation",
        srcProduct: korp3,
        altProduct: 'Изображение школьной доски',
        title: 'Школьная доска',
        description: '35 макаронс в форме школьной доски. Ассорти из 7 учебных вкусов',
        productPrice: 3600,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме школьной доски, чтобы вспоминать уроки и записи на доске.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: молоко, ваниль, клубника, мед, грецкий орех, кокос, карамель',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            milk: 4,
            vanilla: 4,
            strawberry: 4,
            honey: 4,
            walnut: 4,
            coconut: 4,
            caramel: 4,
        }
    },
    {
        vendorCode: '71',
        type: "graduation",
        srcProduct: man2,
        altProduct: 'Изображение танка',
        title: 'Знания – сила',
        description: '24 макаронс в форме танка. Ассорти из 6 интеллектуальных вкусов, каждый – ключ к знаниям',
        productPrice: 3200,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме танка, чтобы вдохновить на погружение в мир знаний.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: шоколад, кофе, мокка, ваниль, карамель, орех',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            chocolate: 4,
            coffee: 4,
            mocha: 4,
            vanilla: 4,
            caramel: 4,
            nut: 4,
        }
    },
    {
        vendorCode: '72',
        srcProduct: bigPiramida,
        type: "graduation",
        altProduct: 'Изображение большой пирамиды макарунс',
        title: 'Звездопад вкусов',
        description: 'Импозантная пирамида из 120 макарунс с праздничными вкусами на ваше великолепное мероприятие',
        productPrice: 9000,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Импозантная пирамида из 120 макарунс с праздничными вкусами на ваше великолепное мероприятие',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 30,
            strawberry: 30,
            vanilla: 30,
            pistachio: 30,
        },
    },
    {
        vendorCode: '73',
        type: "graduation",
        srcProduct: aroundSet,
        altProduct: 'Изображение атласа',
        title: 'Атлас мира',
        description: '45 путешественнических макаронс в форме атласа. Ассорти из 9 мировых вкусов',
        productPrice: 4000,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме атласа, чтобы вспоминать уроки географии и мечтать о путешествиях.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: клубника, малина, лимон, апельсин, ананас, грейпфрут, манго, киви, малина',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            strawberry: 5,
            raspberry: 5,
            lemon: 5,
            orange: 5,
            pineapple: 5,
            grapefruit: 5,
            mango: 5,
            kiwi: 5,
        }
    },
    {
        vendorCode: '74',
        type: "graduation",
        srcProduct: korp3,
        altProduct: 'Изображение школьной формы',
        title: 'Школьная форма',
        description: '28 макаронс в форме школьной формы. Ассорти из 7 "надень-и-учись" вкусов',
        productPrice: 3200,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме школьной формы, чтобы вспоминать дни школьной жизни и занятия.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: клубника, малина, лимон, черника, грецкий орех, мед, кокос',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            strawberry: 4,
            raspberry: 4,
            lemon: 4,
            blueberry: 4,
            walnut: 4,
            honey: 4,
            coconut: 4,
        }
    },
    {
        vendorCode: '75',
        type: 'birthday',
        srcProduct: child4,
        altProduct: 'Изображение воздушных шаров',
        title: 'Веселые шарики',
        description: '24 макаронс в форме воздушных шаров. Ассорти из 6 праздничных вкусов',
        productPrice: 2800,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме воздушных шаров, чтобы придать яркости вашему дню рождения.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: клубника, вишня, лимон, малина, апельсин, ананас',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            strawberry: 4,
            cherry: 4,
            lemon: 4,
            raspberry: 4,
            orange: 4,
            pineapple: 4,
        }
    },
    {
        vendorCode: '76',
        type: 'birthday',
        srcProduct: child1,
        altProduct: 'Изображение торта',
        title: 'Праздничный торт',
        description: '30 макаронс в форме торта. Ассорти из 7 сладких вкусов',
        productPrice: 3200,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме торта, чтобы добавить волшебства и вкуса вашему дню рождения.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: шоколад, ваниль, карамель, клубника, малина, апельсин, кокос',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            chocolate: 4,
            vanilla: 4,
            caramel: 4,
            strawberry: 4,
            raspberry: 4,
            orange: 4,
            coconut: 4,
        }
    },
    {
        vendorCode: '77',
        type: 'birthday',
        srcProduct: child5,
        altProduct: 'Изображение подарка',
        title: 'Подарочная коробка',
        description: '36 макаронс в форме подарка. Ассорти из 9 праздничных вкусов',
        productPrice: 3500,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме подарка, чтобы сделать ваш день рождения еще более особенным.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, клубника, малина, лимон, апельсин, вишня, ананас, грейпфрут, манго',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            strawberry: 4,
            raspberry: 4,
            lemon: 4,
            orange: 4,
            cherry: 4,
            pineapple: 4,
            grapefruit: 4,
            mango: 4,
        }
    },
    {
        vendorCode: '78',
        type: 'birthday',
        srcProduct: setTo16,
        altProduct: 'Изображение конфетти',
        title: 'Сладкое конфетти',
        description: '28 макаронс в форме конфетти. Ассорти из 7 радужных вкусов',
        productPrice: 3000,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме конфетти, чтобы добавить ярких красок и веселья на ваш день рождения.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: клубника, лимон, апельсин, малина, грейпфрут, манго, черника',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            strawberry: 4,
            lemon: 4,
            orange: 4,
            raspberry: 4,
            grapefruit: 4,
            mango: 4,
            blueberry: 4,
        }
    },
    {
        vendorCode: '81',
        type: 'birthday',
        srcProduct: mart1,
        altProduct: 'Изображение конфетти',
        title: 'Веселое конфетти',
        description: '28 макаронс в форме конфетти. Ассорти из 7 праздничных вкусов',
        productPrice: 3100,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме конфетти, чтобы добавить радости и веселья на ваш день рождения.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: клубника, вишня, малина, апельсин, лимон, грейпфрут, манго',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            strawberry: 4,
            cherry: 4,
            raspberry: 4,
            orange: 4,
            lemon: 4,
            grapefruit: 4,
            mango: 4,
        }
    },
    {
        vendorCode: '79',
        type: 'birthday',
        srcProduct: mart2,
        altProduct: 'Изображение свечи',
        title: 'Свеча желаний',
        description: '32 макаронс в форме свечи. Ассорти из 8 вдохновляющих вкусов',
        productPrice: 3300,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме свечи, чтобы озарить ваш день рождения светом вкусов и радости.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, клубника, малина, апельсин, лимон, вишня, манго, кокос',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            strawberry: 4,
            raspberry: 4,
            orange: 4,
            lemon: 4,
            cherry: 4,
            mango: 4,
            coconut: 4,
        }
    },
    {
        vendorCode: '80',
        type: 'birthday',
        srcProduct: mart3,
        altProduct: 'Изображение праздничной шапки',
        title: 'Праздничная шапка',
        description: '36 макаронс в форме праздничной шапки. Ассорти из 9 ярких вкусов',
        productPrice: 3600,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме праздничной шапки, чтобы добавить праздничности и веселья на ваш день рождения.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: клубника, малина, апельсин, вишня, ананас, грейпфрут, киви, манго, малина',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            strawberry: 4,
            raspberry: 4,
            orange: 4,
            cherry: 4,
            pineapple: 4,
            grapefruit: 4,
            kiwi: 4,
            mango: 4,
        }
    },
    {
        vendorCode: '82',
        type: 'anniversary',
        srcProduct: mart1,
        altProduct: 'Изображение бабочки',
        title: 'Вольный полет юбилея',
        description: '22 макаронс в форме круга с бабочковым декором. Ассорти из 6 вдохновляющих вкусов, каждый – символ вольного духа юбиляра',
        productPrice: 3300,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме круга с бабочковым декором, чтобы подчеркнуть вольный и свободный дух юбиляра.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: клубника, лимон, апельсин, вишня, ананас, малина',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            strawberry: 4,
            lemon: 4,
            orange: 4,
            cherry: 4,
            pineapple: 4,
            raspberry: 4,
        }
    },
    {
        vendorCode: '83',
        type: 'anniversary',
        srcProduct: mart2,
        altProduct: 'Изображение лаконичных линий',
        title: 'Элегантная грация юбилея',
        description: '24 макаронс в форме круга с лаконичными линиями. Ассорти из 6 изысканных вкусов, каждый – подчеркнутая грация юбиляра',
        productPrice: 3100,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс с лаконичными линиями в форме круга, чтобы увековечить непередаваемую грацию юбиляра.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, клубника, малина, черника, мята, лимон',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            strawberry: 4,
            raspberry: 4,
            blueberry: 4,
            mint: 4,
            lemon: 4,
        }
    },
    {
        vendorCode: '84',
        type: 'anniversary',
        srcProduct: aroundSet,
        altProduct: 'Изображение кофейной чашки',
        title: 'Вдохновляющий юбилей',
        description: '32 макаронс в форме кофейной чашки. Ассорти из 8 изысканных вкусов, каждый – как аромат кофейного утра юбиляра',
        productPrice: 3400,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме кофейной чашки с ароматами кофейного утра, чтобы вдохновить и поблагодарить юбиляра.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: кофе, ваниль, какао, карамель, орех, молоко, кокос, миндаль',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            coffee: 4,
            vanilla: 4,
            cocoa: 4,
            caramel: 4,
            nut: 4,
            milk: 4,
            coconut: 4,
            almond: 4,
        }
    },
    {
        vendorCode: '85',
        type: 'anniversary',
        srcProduct: mart4,
        altProduct: 'Изображение подковы',
        title: 'Удача и радость юбилея',
        description: '36 макаронс в форме подковы. Ассорти из 9 счастливых вкусов, каждый – символ удачи и радости юбиляра',
        productPrice: 3500,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме подковы, чтобы подарить удачу и радость на юбилей.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: клубника, малина, вишня, апельсин, лимон, грейпфрут, манго, киви, гранат',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            strawberry: 4,
            raspberry: 4,
            cherry: 4,
            orange: 4,
            lemon: 4,
            grapefruit: 4,
            mango: 4,
            kiwi: 4,
            pomegranate: 4,
        }
    },
    {
        vendorCode: '81',
        type: 'anniversary',
        srcProduct: mart5,
        altProduct: 'Изображение звезды',
        title: 'Сияние юбилея',
        description: '20 макаронс в форме звезды. Ассорти из 5 ярких вкусов, каждый – сверкающая звезда юбилея',
        productPrice: 3000,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме звезды, чтобы подчеркнуть яркий юбилей и сияние важного события.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: ваниль, клубника, малина, лимон, апельсин',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            vanilla: 4,
            strawberry: 4,
            raspberry: 4,
            lemon: 4,
            orange: 4,
        }
    },
    {
        vendorCode: '86',
        type: 'anniversary',
        srcProduct: mart1,
        altProduct: 'Изображение кофейной чашки',
        title: 'И снова 32',
        description: '32 макаронс в форме кофейной чашки. Ассорти из 8 изысканных вкусов, каждый – как аромат кофейного утра юбиляра',
        productPrice: 3400,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Макаронс в форме кофейной чашки с ароматами кофейного утра, чтобы вдохновить и поблагодарить юбиляра.',
        compound: 'Сахар, миндальная мука, белки яиц, ароматизаторы: кофе, ваниль, какао, карамель, орех, молоко, кокос, миндаль',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            coffee: 4,
            vanilla: 4,
            cocoa: 4,
            caramel: 4,
            nut: 4,
            milk: 4,
            coconut: 4,
            almond: 4,
        }
    },
];

export { productsPopular }