import hard from '../../image/popular-sets/hard.png';
import aroundSet from '../../image/popular-sets/aroundSet.png';
import beauty from '../../image/popular-sets/beauty.png';
import bigSet from '../../image/popular-sets/BigSet.png';
import setTo9 from '../../image/popular-sets/setTo9.png';
import setTo16 from '../../image/popular-sets/SetTo16.png';


const productsPopular = [
    {
        vendorCode: '1',
        srcProduct: hard,
        altProduct: 'Изображение сердца',
        title: 'Сердце',
        description: '24 штуки в коробке в виде сердца. Ассорти из 6 вкусов',
        productPrice: 2800,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Кондитерское изделие макаронс в виде сердца',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е124, Е150d, ароматизаторы: ванилин, банан, клубника, карамель, манго, виноград',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 4,
            orange: 4,
            tangerine: 4,
            chocolate: 8,
        },
    },
    {
        vendorCode: '2',
        srcProduct: aroundSet,
        altProduct: 'Изображение круглого набора',
        title: 'Круглый набор',
        description: '40 макаронс в круглой коробке с персональной надписью',
        productPrice: 3900,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс в круглой коробке с персональной надписью',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е124, Е150d, ароматизаторы: ванилин, клубника, манго, виноград',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 7,
            orange: 7,
            tangerine: 7,
            chocolate: 19,
        },
    },
    {
        vendorCode: '3',
        srcProduct: beauty,
        altProduct: 'Изображение макаронс',
        title: 'Красота спасёт мир',
        description: 'Набор 16 шт. Вкусы: клубника - базилик, кокос, голубой сыр, пармезан',
        productPrice: 750,
        delivery: false,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс вкусов: клубника - базилик, кокос, голубой сыр, пармезан',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е124, Е150d, ароматизаторы: ванилин, клубника, кокос, сырный',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 3,
            orange: 3,
            tangerine: 3,
            chocolate: 7,
        },
    },
    {
        vendorCode: '4',
        srcProduct: setTo9,
        altProduct: 'Изображение набора макаронс из 9шт',
        title: 'Набор на 9',
        description: 'Набор из 9 штук в квадратной коробке. Вкусы: шоколад, фисташка, вишня',
        productPrice: 950,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс вкусов: шоколад, фисташка, вишня',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е150d, ароматизаторы: ванилин, шоколадный, фисташковый, вишневый',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 6,
            orange: 6,
            tangerine: 6,
            chocolate: 22,
        },
    },
    {
        vendorCode: "5",
        srcProduct: setTo16,
        altProduct: "Изображение набора макаронс из 16шт",
        title: "Набор на 16",
        description:
            "Набор 16 шт. Вкусы: соленая карамель, голубой сыр, пармезан, шоколад",
        productPrice: "1500",
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: "Описание продукта",
        compound: "Состав продукта",
        storageCondition: "Условия хранения",
        tastes: {
            apple: 0,
            orange: 0,
            tangerine: 0,
            chocolate: 16,
        },
    },
    {
        vendorCode: "6",
        srcProduct: bigSet,
        altProduct: "Изображение большого набора макаронс",
        title: "Круглый набор",
        description: "40 макаронс в круглой коробке с персональной надписью",
        productPrice: "3900",
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: "Описание продукта",
        compound: "Состав продукта",
        storageCondition: "Условия хранения",
        tastes: {
            apple: 15,
            orange: 10,
            tangerine: 5,
            chocolate: 10,
        },
    },
    {
        vendorCode: '7',
        srcProduct: setTo9,
        altProduct: 'Изображение набора макаронс из 9шт',
        title: 'Набор на 9',
        description: 'Набор из 9 штук в квадратной коробке. Вкусы: шоколад, фисташка, вишня',
        productPrice: 950,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс вкусов: шоколад, фисташка, вишня',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е150d, ароматизаторы: ванилин, шоколадный, фисташковый, вишневый',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 6,
            orange: 6,
            tangerine: 6,
            chocolate: 22,
        },
    },
    {
        vendorCode: '8',
        srcProduct: beauty,
        altProduct: 'Изображение макаронс',
        title: 'Красота спасёт мир',
        description: 'Набор 16 шт. Вкусы: клубника - базилик, кокос, голубой сыр, пармезан',
        productPrice: 750,
        delivery: false,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс вкусов: клубника - базилик, кокос, голубой сыр, пармезан',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е124, Е150d, ароматизаторы: ванилин, клубника, кокос, сырный',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 3,
            orange: 3,
            tangerine: 3,
            chocolate: 7,
        },
    },
];

export { productsPopular }