import hard from '../../image/popular-sets/hard.png';
import aroundSet from '../../image/popular-sets/aroundSet.png';
import beauty from '../../image/popular-sets/beauty.png';
import bigSet from '../../image/popular-sets/BigSet.png';
import setTo9 from '../../image/popular-sets/setTo9.png';
import setTo16 from '../../image/popular-sets/SetTo16.png';

import bigPiramida from '../../image/popular-sets/bigPiramida.png';
import piramida from '../../image/popular-sets/piramida.png';
import forGuests from '../../image/popular-sets/forGuests.png';
import henParty from '../../image/popular-sets/hen-party.png';
import name from '../../image/popular-sets/name.png';


const productsPopular = [
    {
        vendorCode: '1',
        type: 'popular',
        srcProduct: hard,
        altProduct: 'Изображение сердца',
        title: 'Сердце',
        description: '24 штуки в коробке в виде сердца. Ассорти из 6 вкусов',
        productPrice: 2800,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Кондитерское изделие макаронс в виде сердца',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е124, Е150d, ароматизаторы: ванилин, банан, клубника, карамель, манго, виноград',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 4,
            orange: 4,
            tangerine: 4,
            chocolate: 8,
        },
    },
    {
        vendorCode: '2',
        type: 'popular',
        srcProduct: aroundSet,
        altProduct: 'Изображение круглого набора',
        title: 'Круглый набор',
        description: '40 макаронс в круглой коробке с персональной надписью',
        productPrice: 3900,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс в круглой коробке с персональной надписью',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е124, Е150d, ароматизаторы: ванилин, клубника, манго, виноград',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 7,
            orange: 7,
            tangerine: 7,
            chocolate: 19,
        },
    },
    {
        vendorCode: '3',
        type: 'popular',
        srcProduct: beauty,
        altProduct: 'Изображение макаронс',
        title: 'Красота спасёт мир',
        description: 'Набор 16 шт. Вкусы: клубника - базилик, кокос, голубой сыр, пармезан',
        productPrice: 750,
        delivery: false,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс вкусов: клубника - базилик, кокос, голубой сыр, пармезан',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е124, Е150d, ароматизаторы: ванилин, клубника, кокос, сырный',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 3,
            orange: 3,
            tangerine: 3,
            chocolate: 7,
        },
    },
    {
        vendorCode: '4',
        type: 'popular',
        srcProduct: setTo9,
        altProduct: 'Изображение набора макаронс из 9шт',
        title: 'Набор на 9',
        description: 'Набор из 9 штук в квадратной коробке. Вкусы: шоколад, фисташка, вишня',
        productPrice: 950,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс вкусов: шоколад, фисташка, вишня',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е150d, ароматизаторы: ванилин, шоколадный, фисташковый, вишневый',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 6,
            orange: 6,
            tangerine: 6,
            chocolate: 22,
        },
    },
    {
        vendorCode: "5",
        type: 'popular',
        srcProduct: setTo16,
        altProduct: "Изображение набора макаронс из 16шт",
        title: "Набор на 16",
        description:
            "Набор 16 шт. Вкусы: соленая карамель, голубой сыр, пармезан, шоколад",
        productPrice: "1500",
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: "Описание продукта",
        compound: "Состав продукта",
        storageCondition: "Условия хранения",
        tastes: {
            apple: 0,
            orange: 0,
            tangerine: 0,
            chocolate: 16,
        },
    },
    {
        vendorCode: "6",
        type: 'popular',
        srcProduct: bigSet,
        altProduct: "Изображение большого набора макаронс",
        title: "Круглый набор",
        description: "40 макаронс в круглой коробке с персональной надписью",
        productPrice: "3900",
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: "Описание продукта",
        compound: "Состав продукта",
        storageCondition: "Условия хранения",
        tastes: {
            apple: 15,
            orange: 10,
            tangerine: 5,
            chocolate: 10,
        },
    },
    {
        vendorCode: '7',
        type: 'popular',
        srcProduct: setTo9,
        altProduct: 'Изображение набора макаронс из 9шт',
        title: 'Набор на 9',
        description: 'Набор из 9 штук в квадратной коробке. Вкусы: шоколад, фисташка, вишня',
        productPrice: 950,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс вкусов: шоколад, фисташка, вишня',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е150d, ароматизаторы: ванилин, шоколадный, фисташковый, вишневый',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 6,
            orange: 6,
            tangerine: 6,
            chocolate: 22,
        },
    },
    {
        vendorCode: '8',
        type: 'popular',
        srcProduct: beauty,
        altProduct: 'Изображение макаронс',
        title: 'Красота спасёт мир',
        description: 'Набор 16 шт. Вкусы: клубника - базилик, кокос, голубой сыр, пармезан',
        productPrice: 750,
        delivery: false,
        pickup: true,
        present: true,
        detailedDescription: 'Кондитерское изделие макаронс вкусов: клубника - базилик, кокос, голубой сыр, пармезан',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е124, Е150d, ароматизаторы: ванилин, клубника, кокос, сырный',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 3,
            orange: 3,
            tangerine: 3,
            chocolate: 7,
        },
    },
    {
        vendorCode: '9',
        srcProduct: bigPiramida,
        type: 'wedding',
        altProduct: 'Изображение большой пирамиды макарунс',
        title: 'Большая пирамида',
        description: 'Импозантная пирамида из 120 макарунс на ваше великолепное мероприятие',
        productPrice: 9000,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Импозантная пирамида из 120 макарунс на ваше великолепное мероприятие',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 30,
            strawberry: 30,
            vanilla: 30,
            pistachio: 30,
        },
        type: 'wedding'
    },
    {
        vendorCode: '10',
        srcProduct: piramida,
        type: 'wedding',
        altProduct: 'Изображение пирамиды макарунс',
        title: 'Пирамида макарунс',
        description: 'Красочная пирамида из 60 макарунс с разнообразными вкусами',
        productPrice: 5000,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Красочная пирамида из 60 макарунс с разнообразными вкусами',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 20,
            raspberry: 15,
            lemon: 10,
            coconut: 15,
        },
        type: 'wedding'
    },
    {
        vendorCode: '11',
        srcProduct: forGuests,
        type: 'wedding',
        altProduct: 'Изображение макарунс для гостей',
        title: 'Макаруны для гостей',
        description: 'Индивидуальные наборы макарунс для каждого гостя на вашем торжестве',
        productPrice: 1300,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Индивидуальные наборы макарунс для каждого гостя на вашем торжестве',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 12,
            vanilla: 12,
            strawberry: 12,
            pistachio: 12,
        },
        type: 'wedding'
    },
    {
        vendorCode: '12',
        srcProduct: henParty,
        type: 'wedding',
        altProduct: 'Изображение макарунс для девичника',
        title: 'Макаруны для девичника',
        description: 'Оригинальные макарунс для яркого и веселого девичника',
        productPrice: 1800,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Оригинальные макарунс для яркого и веселого девичника',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            raspberry: 15,
            passionFruit: 10,
            blueberry: 10,
            lime: 10,
        },
        type: 'wedding'
    },
    {
        vendorCode: '13',
        srcProduct: name,
        type: 'wedding',
        altProduct: 'Изображение макарунс с именами',
        title: 'Макаруны с именами',
        description: 'Уникальные макарунс с именами ваших гостей',
        productPrice: 2500,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Уникальные макарунс с именами ваших гостей',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 10,
            raspberry: 10,
            lemon: 10,
            vanilla: 10,
        },
        type: 'wedding'
    },
    {
        vendorCode: '14',
        type: 'popular',
        type: 'wedding',
        srcProduct: hard,
        altProduct: 'Изображение сердца',
        title: 'Сердце',
        description: '24 штуки в коробке в виде сердца. Ассорти из 6 вкусов. Прекрасный выбор для любого праздника',
        productPrice: 2800,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Кондитерское изделие макаронс в виде сердца',
        compound: 'Сахар, миндальная мука, белки яиц, красители: Е102, Е122, Е124, Е150d, ароматизаторы: ванилин, банан, клубника, карамель, манго, виноград',
        storageCondition: 'Хранить при температуре от +2 до +4 градусов Цельсия',
        tastes: {
            apple: 4,
            orange: 4,
            tangerine: 4,
            chocolate: 8,
        },
    },
    {
        vendorCode: '15',
        srcProduct: piramida,
        type: 'wedding',
        altProduct: 'Изображение пирамиды макарунс',
        title: 'Пирамида макарунс',
        description: 'Красочная пирамида из 60 макарунс с разнообразными вкусами',
        productPrice: 5000,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Красочная пирамида из 60 макарунс с разнообразными вкусами',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 20,
            raspberry: 15,
            lemon: 10,
            coconut: 15,
        },
        type: 'wedding'
    },
    {
        vendorCode: '16',
        srcProduct: forGuests,
        type: 'wedding',
        altProduct: 'Изображение макарунс для гостей',
        title: 'Макаруны для гостей',
        description: 'Индивидуальные наборы макарунс для каждого гостя на вашем торжестве',
        productPrice: 1300,
        delivery: true,
        pickup: true,
        present: true,
        detailedDescription: 'Индивидуальные наборы макарунс для каждого гостя на вашем торжестве',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            chocolate: 12,
            vanilla: 12,
            strawberry: 12,
            pistachio: 12,
        },
        type: 'wedding'
    },
    {
        vendorCode: '17',
        srcProduct: henParty,
        type: 'wedding',
        altProduct: 'Изображение макарунс для девичника',
        title: 'Макаруны для девичника',
        description: 'Оригинальные макарунс для яркого и веселого девичника',
        productPrice: 1800,
        delivery: true,
        pickup: true,
        present: false,
        detailedDescription: 'Оригинальные макарунс для яркого и веселого девичника',
        compound: 'Состав продукта',
        storageCondition: 'Условия хранения',
        tastes: {
            raspberry: 15,
            passionFruit: 10,
            blueberry: 10,
            lime: 10,
        },
        type: 'wedding'
    },
];

export { productsPopular }